name: ecomate
description: "AI Waste Segregation Assistant"
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.6
  image_picker: ^1.0.4
  flutter_dotenv: ^5.1.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^11.0.0
  permission_handler: ^11.3.0
  http: ^1.2.0
  url_launcher: ^6.2.5
  firebase_core: ^2.32.0
  firebase_storage: ^11.6.0
  firebase_database: ^10.4.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.14.0
  google_fonts: ^6.1.0
  uuid: ^4.2.2
  cloudinary: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/