// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-CmRQrMyiswajcey2pTNiooNBjR-Rjdg',
    appId: '1:172694023486:web:4eb47c9c075fc25cd0106f',
    messagingSenderId: '172694023486',
    projectId: 'ecomate-64a5b',
    authDomain: 'ecomate-64a5b.firebaseapp.com',
    storageBucket: 'ecomate-64a5b.firebasestorage.app',
    measurementId: 'G-39S212C6JF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd2WsNK0uXEpzLKdsCLmTwF05o9MS1spk',
    appId: '1:172694023486:android:8ea92e1ed724aa29d0106f',
    messagingSenderId: '172694023486',
    projectId: 'ecomate-64a5b',
    storageBucket: 'ecomate-64a5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpp0grwFR9igJrNIKrMGYukcef2NdM2_8',
    appId: '1:172694023486:ios:fa5b08fdd7df19c8d0106f',
    messagingSenderId: '172694023486',
    projectId: 'ecomate-64a5b',
    storageBucket: 'ecomate-64a5b.firebasestorage.app',
    iosBundleId: 'com.example.ecomate2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpp0grwFR9igJrNIKrMGYukcef2NdM2_8',
    appId: '1:172694023486:ios:fa5b08fdd7df19c8d0106f',
    messagingSenderId: '172694023486',
    projectId: 'ecomate-64a5b',
    storageBucket: 'ecomate-64a5b.firebasestorage.app',
    iosBundleId: 'com.example.ecomate2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-CmRQrMyiswajcey2pTNiooNBjR-Rjdg',
    appId: '1:172694023486:web:b905a57146cebc30d0106f',
    messagingSenderId: '172694023486',
    projectId: 'ecomate-64a5b',
    authDomain: 'ecomate-64a5b.firebaseapp.com',
    storageBucket: 'ecomate-64a5b.firebasestorage.app',
    measurementId: 'G-T2T9V9ZZKG',
  );

}